language: node_js

sudo: false

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

      
node_js:
  - "6.1.0"

after_success:
  - |
      curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/dwdraju/node-devops-test/trigger/6775840b-1d72-412e-a4e1-e3bc9ade5a05/
